apiVersion: v1
kind: Service
metadata:
  name: api # On utilise ce nom pour matcher le YAML front et la meme adresse que docker compose (http://api:8000)
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000 # celui de http://api:8000
      targetPort: 8000 # celui du dockerfile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: devermyst/ia-tp:latest
        imagePullPolicy: IfNotPresent # cherche l'image en local
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        env: # pour déposer les messages - répété dans worker.yaml pour écouter les messages
        - name: CELERY_BROKER_URL
          value: "pyamqp://guest:guest@rabbitmq-service:5672//"
